[bar.default]
center = [ "bar", "media", "audio_visualizer" ]
end = [ "tray", "notifications", "network", "battery", "session", "clock" ]
font_family = "Inter"
margin_ends = 0
radius = 0
shadow = false
start = [ "launcher", "workspaces", "weather" ]
thickness = 32

[location]
address = "Jizzakh, Uzbekistan"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugin_settings."nzlov/daily-wallpaper"]
source = "nasa"

[plugin_settings."ycf/mawaqit"]
city = "Jizzakh"
country = "UZ"
school = "1"

[plugins]
enabled = [ "damian-ds7/battery-threshold", "noctalia/timer" ]

[shell]
font_family = "Inter"
polkit_agent = true

    [shell.panel]
    polkit_placement = "attached"

[theme]
builtin = "Catppuccin"
community_palette = "Doomed"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "hyprland", "kcolorscheme", "qt" ]

[wallpaper]
directory = "~/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/akbar/Pictures/Wallpapers/wallhaven-lydd6r_1920x1080.png"

    [wallpaper.last]
    path = "/home/akbar/Pictures/Wallpapers/wallhaven-lydd6r_1920x1080.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/akbar/Pictures/Wallpapers/wallhaven-lydd6r_1920x1080.png"

[widget.bar]
type = "noctalia/timer:bar"
